apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-serv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: calc-serv
          image: oleglola/calc-serv:2
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: WORKER_HOST
              value: worker-client-ip-service
            - name: WORKER_PORT
              value: '9000'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
